### ISSUE TITLE
specify sub-path

### ISSUE THREAD

**Issue by sgohl** [camunda/vault-dump-kv2#2]
may you add the possibility to specify a sub-path  to recursively dump?

trying to set it like this failed:

```
root@da686ccbe390:/# export VAULT_DUMP_MOUNTPOINT="/kv/prod/"

root@da686ccbe390:/# python /opt/vault-dump-kv2.py 
#
# vault-dump-kv2.py backup
# backup date: 2020-04-03 12:52:21.037428 UTC
# VAULT_DUMP_MOUNTPOINT setting: /kv/online/
# STDIN encoding: utf-8
# STDOUT encoding: utf-8
#
# WARNING: not guaranteed to be consistent!
#
Recursing into path prefix ""
Traceback (most recent call last):
  File "/opt/vault-dump-kv2.py", line 51, in <module>
    recurse_secrets('', vault_dump_mountpoint)
  File "/opt/vault-dump-kv2.py", line 30, in recurse_secrets
    keys = client.secrets.kv.v2.list_secrets(path_prefix, mount_point=mountpoint)['data']['keys']
  File "/usr/local/lib/python3.8/site-packages/hvac/api/secrets_engines/kv_v2.py", line 301, in list_secrets
    response = self._adapter.list(
  File "/usr/local/lib/python3.8/site-packages/hvac/adapters.py", line 142, in list
    return self.request('list', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/hvac/adapters.py", line 272, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/hvac/utils.py", line 38, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors)
hvac.exceptions.InvalidPath: {"request_id":"37c70dfa-62c7-4ad4-cba3-cff2cff678b2","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv list' for this operation."],"auth":null}
```

**Comment by cmur2** [comment]
Hi, yes the `VAULT_DUMP_MOUNTPOINT` can only be used to specify a secret engine mount path. I'm working on a change in https://github.com/camunda/vault-dump-kv2/pull/4 that tries to cover your use case.

**Comment by cmur2** [comment]
@sgohl in case you still have a usecase for the functionality (sorry for the late response) you can now check the modified script in https://github.com/camunda/vault-dump-kv2/blob/master/vault-dump-kv2.py and maybe give it a try :)
