### ISSUE TITLE
backup all secrets

### ISSUE THREAD

**Issue by pratamapuguh** [camunda/vault-dump-kv2#5]
hi, I have many secrets in my vault, could I backup all of those secrets at one time?
I used 
`export VAULT_DUMP_MOUNTPOINT="/secrets/"`

but it was failed:
```
Recursing into path prefix ""
Traceback (most recent call last):
  File "vault-dump-kv2.py", line 53, in <module>
    recurse_secrets(vault_dump_path_prefix, vault_dump_mountpoint)
  File "vault-dump-kv2.py", line 30, in recurse_secrets
    keys = client.secrets.kv.v2.list_secrets(path_prefix, mount_point=mountpoint)['data']['keys']
  File "/usr/local/lib/python3.8/dist-packages/hvac/api/secrets_engines/kv_v2.py", line 298, in list_secrets
    return self._adapter.list(
  File "/usr/local/lib/python3.8/dist-packages/hvac/adapters.py", line 146, in list
    return self.request('list', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hvac/adapters.py", line 342, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hvac/adapters.py", line 304, in request
    utils.raise_for_error(
  File "/usr/local/lib/python3.8/dist-packages/hvac/utils.py", line 43, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors, method=method, url=url)
hvac.exceptions.InvalidPath: no handler for route 'secrets/metadata/', on list http://127.0.0.1:8200/v1/secrets/metadata
```

**Comment by cmur2** [comment]
Do you have a KV v2 secrets engine mounted at `/secrets/` in your Vault? You can find out by the output of `vault secrets list`, it needs to return a line like `secrets/      kv      kv_????`.

**Comment by pratamapuguh** [comment]
Thank you for the answer, seems like I have to define one by one manually. Closing the issue.
